= APM Alerts Creation Scripts

Kloudfuse shares these Python scripts so you can create APM alerts and contact points using existing CSV files. Use these scripts to convert NRQL alerts to Grafana alerts. 

[TIP]
CSV files must use a fixed format. Ensure that you configure your source files correctly.  

== Prerequisites

- Python 3.x
- Required Python packages: use the `requirements.txt` file to install all the packages, using `pip3 install -r requirements.txt`.
- Access to the Grafana instance 
- CSV file for `create_alerts.py`: `sample_alerts_config.csv`
- CSV file for c`reate_contact_points.py`: `sample_contact_points.csv`
- `SERVICE_ID_LABELS_AGGR` (["availability_zone", "cloud_account_id", "kf_platform", "kube_cluster_name", "kube_namespace", "project", "region", "service_name"]) : List of labels that must be customised for each customer

== Command Arguments

Arguments Definitions:

[[a]]
`-a, --grafana-server`:: Grafana server address, such as `https://<KFUSE_DNS_NAME>grafana`

[[u]]
`-u, --grafana-username`:: Grafana username; default: `admin`

[[p]]
`-p, --grafana-passwd`:: Grafana password; default: `password`

[[t]]
`-t, --threshold_values_file`:: CSV file with `config` for alert rules; specify the absolute path

[[c]]
`-c, --contact_points_file`:: CSV file with `config` for contact points; specify the absolute path

[[alerts]]
== Create APM Alerts

.Create Alerts
====
[,code]
----
sh
python3 create_alerts.py --grafana_server "https://<KFUSE_DNS_NAME>/grafana" \
  --threshold_values_file ./files/sample_alerts_config.csv \
  --grafana_username admin -p <your-password>
----
====

=== CSV Configuration File

Use `sample_alerts_config.csv` with `create_alerts.py` script to define alert rules. 
You cann convert NRQL alerts to Grafana alerts using the CSV file.

.Structure of sample_alerts_config.csv
====
[,code]
----
sh
apm_trigger,service_name,span_name_pattern,span_name_matcher_op,threshold_operator,threshold_value,reducer,service_id_labels
http_requests,frontendproxy,ingress,=~,<,5,max,availability_zone=us-west1-a;cloud_account_id=12345
----
====

==== Field Descriptions of sample_alerts_config.csv

These are the field descriptions for `sample_alerts_config.csv`:

[[apm_trigger]]
`apm_trigger`:: Type of alert: `http_requests`, `error_rate`, `apdex`, and so on.
[[service_name]]
`service_name`:: The name of the service that generates the alert.
[[span_name_pattern]]
`span_name_pattern`:: Specifies the span to monitor.
[[span_name_matcher_op]]
`span_name_matcher_op`:: The operation for matching the span: =, =~ for regex, and so on.
[[threshold_operator]]
`threshold_operator`:: Alert threshold comparison: <, >, or =.
[[threshold_value]]
`threshold_value`:: The value that triggers the alert.
[[reducer]]
`reducer`::  Function applied to metric values: max, min, and so on.
[[service_id_labels]]
`service_id_labels`::  Key-value pairs that identify the service, separated by semicolon. 
+
See the *APM Services* page for each service to find this information. 
+
[[service_id_labels-example]]
Example::: `availability_zone=us-west1-a;cloud_account_id=12345`

[[contact-points]]
== Create Alert Contact Points

.Create Contact Points
====
[,code]
----
sh
python3 create_contact_points.py -g "https://<KFUSE_DNS_NAME>/grafana"
-c ./files/sample_contact_points.csv
----
====

=== CSV Configuration File

Use `sample_contact_points.csv` with `create_contact_points.py` to define contact points.

.Structure of the sample_contact_points.csv file
====
[,code]
----
sh
contact_point_name,type,receiver,template_title_file,template_body_file
alerts-webui,slack,https://hooks.slack.com/services/xxxx/yyyy/zzzz,default_slack_template_title,default_slack_template_body
incore,email,sample_email@email.com,default_email_template_title,default_email_template_body
----
====

The CSV file defines the contact point name, type, and receiver. The template title and body files define the title and body of the alert.

==== Field Descriptions of sample_contact_points.csv

These are the field descriptions for `sample_contact_points.csv`:

[[contact_point_name]]
`contact_point_name`:: Identifier for the contact point, such as `alerts-webui`, `incore`, and so on.

[[type]]
`type`:: The type of contact point, such as Slack, E-mail, and so on.

[[receiver]]
`receiver`:: The recipient endpoint, such as Slack webhook URL or E-mail address.

[[template_title_file]]
`template_title_file`:: The file name for the title template used in notifications; present in the files folder.

[[template_body_file]]
`template_body_file`:: The file name for the body template used in notifications; present in the files folder.

== Converting NRQL Alerts to Grafana Alerts

Use the `sample_alerts_config.csv` file to convert NRQL alerts to Grafana alerts.

=== Trigger Types

Kloudfuse supports the following trigger types: `http_requests`, `error_rate`, `http_throughput`,`apdex`, `average_latency`, `max_latency`, `min_latency`, `p50_latency`, `p75_latency`, `p90_latency`, `p95_latency`, and `p99_latency`.

[NOTE]
Ensure that you correctly map each NRQL Trigger type to one of the Kloudfuse trigger types.

.Simple NRQL Alert
====
[,json]
----
sh
{
  "entity_name": "ACI-PROD-LMS-LIVE",
  "type": "apm_app_metric",
  "condition_scope": "application",
  "enabled": true,
  "policies": [
    {
      "policy_name": "NOC",
      "terms": [
        {
          "name": "ACI-PROD-LMS-LIVE Response Time",
          "duration": "5",
          "operator": "above",
          "priority": "critical",
          "threshold": "3",
          "time_function": "all",
          "metric": "response_time_web"
        }
      ]
    },
  ]
}
----

[[entity_name]]
`entity_name`:: Maps to `service_name` in the CSV. This represents the service generating the alert.

[[policy_name.name]]
`policies[0].policy_name.name`:: Contains the `service_name` followed by the `apm_trigger`. 
+
[NOTE]
You may have to use both the `operator` and `apm_trigger` to determine the APM trigger type. For example, `Response Time` corresponds to `latency`, but there are several available latency types, such as P75, P90, and so on. You must choose one. 

[[operator]]
`policies[0].terms.operator`:: Corresponds to `threshold_operator` in the CSV.  

[[threshold]]
`policies[0].terms.threshold`:: Maps to `threshold_value` in the CSV. The value that triggers the alert notification.
====

.NRQL Alert with Multiple Terms
====
[,json]
----
sh
{
  "nrql_conditions": [
    {
      "policy_name":"NOC",
      "type": "static",
      "name": "ACAC-PROD-FACETS-LMS-LIVE nrql ohs_getuserclient average apm_service_transaction_duration",
      "enabled": true,
      "value_function": "single_value",
      "violation_time_limit_seconds": 259200,
      "terms": [
        {
          "duration": "10",
          "operator": "above",
          "priority": "warning",
          "threshold": "0.015",
          "time_function": "all"
        },
        {
          "duration": "10",
          "operator": "above",
          "priority": "critical",
          "threshold": "0.070",
          "time_function": "all"
        }
      ],
      "nrql": {
        "query": "SELECT average(apm.service.transaction.duration) as value FROM Metric WHERE appName = 'ACAC-PROD-FACETS-LMS-LIVE' and transactionName like 'WebTransaction/Expressjs/POST//ohs/get-user-client'",
        "since_value": "10"
      },
      "signal": {
        "aggregation_window": "60",
        "evaluation_offset": "3",
        "fill_option": "static",
        "fill_value": "0"
      },
      "expiration": {
        "expiration_duration": "3900",
        "open_violation_on_expiration": false,
        "close_violations_on_expiration": true
      },
    }
  ]
}
----

[[appName]]
`nrql.query.appName`:: Maps to `service_name` in the CSV. This represents the service generating the alert.

[[transactionName]]
`nrql.query.transactionName`:: Maps to `spanname` in the CSV. This defines the specific transaction being monitored.

[[average]]
`average(apm.service.transaction.duration)`:: In NRLQ query.
+
Corresponds to the `average_latency` trigger type in Kloudfuse. Represents the average transaction duration for a specific service or span.

[[threshold-value]]
`terms[].threshold`:: Maps to `threshold_value` in the CSV, the numerical value that triggers the alert notification.
====

.NRQL Alert for Poorest Performance
====
[,json]
----
sh
 "nrql": {
        "query": "SELECT percentile(duration,99) as value FROM Transaction WHERE appName = 'ACAC-PROD-FACETS-LMS-LIVE' and name = 'WebTransaction/Expressjs/POST//users/sessionv2'",
        "since_value": "60"
      },
----

[[bottom-1-percent]]
`percentile(duration,99)`:: In NRQL query.
+
Corresponds to the `p99_latency` trigger type in Kloudfuse. Represents the 99th percentile of transaction duration, and the latency experienced by the slowest 1% of requests.
====
